site_name: Rest-by-Django

theme: 
  name: 'material'

nav:
  - Home: index.md
  - About: about.md
  - Project_Structure:
     - Virtual Environment: Project_Structure/eventos.md
     - Virtual Environment: Project_Structure/getting_started.md
     - Tests: Project_Structure/tests.md 